baseURL = "https://liveandletlearn.net/"
languageCode = "en-us"
title = "Live and let Learn"
theme = "beautifulhugo"

[Params]
  subtitle = "Living and learning together"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "Michael Nelson"
  email = "absoludity+lll@gmail.com"
  github = "absoludity"
  googleplus = "+MichaelNelson-0"
  twitter = "michaelanelson"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

